openapi: 3.0.0
info:
  title: AI Studio Backend API
  version: 1.0.0
  description: |
    This API powers the AI Studio app (auth + generations).
    Includes JWT authentication and image upload for generations.

servers:
  - url: http://localhost:5000

paths:
  /auth/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        "201":
          description: User created successfully
        "400":
          description: Invalid input

  /auth/login:
    post:
      summary: Log in and receive JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid credentials

  /generations:
    get:
      summary: Get generation history for the logged-in user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful fetch
    post:
      summary: Create a new generation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                prompt: { type: string }
                style: { type: string }
                image: { type: string, format: binary }
      responses:
        "200":
          description: Generation created successfully

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
